[package]
name = "Sevning"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = "0.72.3"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }
toml = "0.8.19"
tracing = "0.1"
tracing-subscriber = "0.3"
