# Application Config
[application]
ip = 'localhost'
port = '8080'
verify = false
password = 'password'

# ApiName - Run Command
[runtimes]
ping = "ping {ip} -c 4"
echo = "echo {内容}"

# Token - Money
[users]
Coaixy_10086 = "100"