# Application Config
[Application]
ip = '0.0.0.0'
port = '8080'
verify = false
password = 'password'

# ApiName - Run Command
[Runtimes]
python_weiban = "python main.py {1} {2} {3}"

# Token - Money
[Users]
Coaixy_10086 = "100"